image: mcr.microsoft.com/dotnet/sdk:7.0

before_script:
  - dotnet restore

stages:          # List of stages for jobs, and their order of execution
  - build-n-test
  # - test
  - deploy

variables:
  AZURE_WA_NAME: "cicd-gitlab-backend-fa-training-system"
  AZURE_WA_USERNAME: "cicd-gitlab-backend-fa-training-system \ cicd-gitlab-backend-fa-training-system"
  AZURE_WA_PASSWORD: "xLB7BJdAG2wYyACJJYX6aoGSE1B2hPKGPK5cfum717MaZ4L5u4AcBrfEm4bh"
  AZURE_WA_FTP_URL: "ftps://waws-prod-sg1-079.ftp.azurewebsites.windows.net/site/wwwroot"

build-and-test-job:       # This job runs in the build stage, which runs first.
  stage: build-n-test
  script:
    - echo "Compiling the code..." 
    - dotnet build --no-restore
    # - cd Apis
    # - dotnet run --project webapi
    # make sure health check are 200
    # - Get https://localhost:5001/healthchecks
    - echo "Compile completed build."
    - echo "Running unit tests... This will take about 60 seconds."
    - dotnet test --no-restore
    - echo "Code coverage is 90%"
    # unit-test-job:   # This job runs in the test stage.
    #   stage: test    # It only starts when the job in the build stage completes successfully.
    #   script:
    #     - echo "Running unit tests... This will take about 60 seconds."
    #     - echo "Code coverage is 90%"

    # deploy-job:      # This job runs in the deploy stage.
    #   stage: deploy  # It only runs when both jobs in the test stage complete successfully.
    #   script:
    #     - echo "Deploying application..."
    #     - echo "Application successfully deployed."

deploy:
  stage: deploy
  image: ubuntu
  script:
    -sudo apt-get update
    -sudo apt-get install -y lftp
    - lftp -e "open -u $AZURE_WA_USERNAME,$AZURE_WA_PASSWORD $AZURE_WA_FTP_URL; mirror -R ./build_output /site/wwwroot" -p 21
  environment:
    name: production
  only:
    - master
