cd ..
dotnet test --collect:"XPlat Code Coverage"
reportgenerator -reports:**/**/coverage.cobertura.xml -targetdir:"Tests\CoverageReport" -reporttypes:"Html;JsonSummary;TextSummary" -classfilters:-AutoGeneratedProgram
@echo off

echo Press any key to continue...
pause >nul
echo You pressed a key!