cd ..
dotnet test --collect:"XPlat Code Coverage"
reportgenerator -reports:**/**/coverage.cobertura.xml -targetdir:"Tests\CoverageReport" -reporttypes:"Html;JsonSummary;TextSummary" -classfilters:-AutoGeneratedProgram